SET NAMES 'utf8';

DROP DATABASE IF EXISTS tools;

CREATE DATABASE tools CHARACTER SET utf8 COLLATE utf8_general_ci;

GRANT ALL ON tools.* TO 'observer'@'%' IDENTIFIED BY 'Password1';

USE tools;

CREATE TABLE tools (id INT PRIMARY KEY AUTO_INCREMENT, ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP, tool VARCHAR(25));
