---
- name: T302
  hosts: all
  become: True

  tasks:
    - name: Add records for web and db in `/etc/hosts`
      lineinfile:
        path: /etc/hosts
        regexp: ".*\\s+{{ item }}$"
        line: "{{ hostvars[groups[item][0]]['ansible_default_ipv4']['address'] }} {{ item }}"
        state: present
      loop:
        - web
        - db

- hosts: web
  become: True

  tasks:
    - name: Install Apache web server and PHP
      apt:
        name:
          - apache2
          - libapache2-mod-php
          - php
          - php-mysqlnd
          - git
        state: present
    - name: Remove default index.html file
      file:
        path: /var/www/html/index.html
        state: absent
    - name: Repository checkout
      git:
        repo: 'https://tiger.tuionui.com/dimitar/do-apps'
        dest: /tmp/do-apps
    - name: Copy web files
      copy: 
        src: /tmp/do-apps/app1/web/
        dest: /var/www/html
        remote_src: yes
        directory_mode: yes
    - name: Restart Apache
      service:
        name: apache2
        state: restarted

- hosts: db
  become: true

  handlers:
    - name: Restart MariaDB
      systemd:
        name: mariadb
        daemon_reload: true
        state: restarted

  tasks:
    - name: Install MariaDB and all dependencies
      apt:
        name:
          - mariadb-common
          - mariadb-client
          - mariadb-server
          - git
        state: present
        update_cache: yes
    - name: Start and enable mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
    - name: Configure mariadb
      copy:
        dest: /etc/mysql/mariadb.conf.d/99-custom.cnf
        content: |
          [mysqld]
          bind-address = 0.0.0.0
      notify:
        - Restart MariaDB
    - name: Repository checkout
      git:
        repo: 'https://tiger.tuionui.com/dimitar/do-apps'
        dest: /tmp/do-apps
    - name: Import database
      shell:
        mysql -u root --password=root < /tmp/do-apps/app1/db/db_setup.sql
