t202-1 ansible_host=192.168.99.202 ansible_port=10202 
t202-2 ansible_host=192.168.99.202 ansible_port=11202

[web]
t202-1

[db]
t202-2

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_rsa
